[pic]: Fix `-Wunused-parameter` compiler warning.
* src/preproc/pic/object.cpp (object::point): Fix compiler warning when
  building paranoiacally; don't give an actual parameter a name when
  it's unused.

Fixes:
../src/preproc/pic/object.cpp: In member function ‘virtual void object::set_vertex_number(int)’:
../src/preproc/pic/object.cpp:384:36: error: unused parameter ‘vnum’ [-Werror=unused-parameter]
  384 | void object::set_vertex_number(int vnum)
      |                                ~~~~^~~~